databases:
  - name: hospital_control_app_production
    databaseName: hospital_control_app_production
    user: deployer

services:
  - type: web
    name: hospital_control_app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hospital_control_app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false